# Nixpacks configuration
[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install","bunx drizzle-kit push","bun scripts/migrate-mhtcet.ts"]


[start]
cmd = "bunx drizzle-kit push && bun scripts/migrate-mhtcet.ts"
